spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ict-assets
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql
server:
  port: 9090
security:
  jwt:
    secret: aZt2026-strong-secret-key-ict-assets-jwt-token
    expiration: 86400000
